# Generated by Django 2.0.1 on 2018-06-05 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('atk', models.IntegerField()),
                ('special', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INGRACIA', 'Ingracia'), ('RAELENE', 'Raelene'), ('RIOCARD', 'Riocard'), ('RION', 'Rion')], max_length=64)),
                ('tagline', models.CharField(max_length=64, unique=True)),
                ('image', models.BinaryField(blank=True)),
                ('type', models.CharField(choices=[('COPSE', 'Copse'), ('PYRE', 'Pyre'), ('TERRA', 'Terra'), ('STEEL', 'Steel'), ('STORM', 'Storm')], max_length=64)),
                ('secondary_type', models.CharField(choices=[('COPSE', 'Copse'), ('PYRE', 'Pyre'), ('TERRA', 'Terra'), ('STEEL', 'Steel'), ('STORM', 'Storm')], max_length=64, null=True)),
                ('weapon_type', models.CharField(choices=[('HAMMER', 'Hammer'), ('DAGGER', 'Dagger'), ('AXE', 'Axe'), ('SWORD', 'Sword'), ('WHIP', 'Whip'), ('BRACELET', 'Bracelet'), ('RING', 'Ring'), ('EARRINGS', 'Earrings'), ('BOW', 'Bow'), ('GUN', 'Gun'), ('STAFF', 'Staff'), ('TORCH', 'Torch'), ('WAND', 'Wand'), ('SCEPTER', 'Scepter'), ('FLUTE', 'Flute')], max_length=64)),
                ('base_hp', models.IntegerField()),
                ('base_atk', models.IntegerField()),
                ('base_spd', models.IntegerField()),
                ('base_def', models.IntegerField()),
                ('base_res', models.IntegerField()),
                ('base_atk_name', models.CharField(max_length=64)),
                ('base_def_name', models.CharField(max_length=64)),
                ('base_ult_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Defend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('special', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ultimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('special', models.CharField(max_length=64)),
            ],
        ),
    ]
