# Generated by Django 2.0.1 on 2018-06-05 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('curr_hp', models.IntegerField()),
                ('curr_atk', models.IntegerField()),
                ('curr_spd', models.IntegerField()),
                ('curr_def', models.IntegerField()),
                ('curr_res', models.IntegerField()),
                ('curr_atk_name', models.CharField(max_length=64)),
                ('curr_def_name', models.CharField(max_length=64)),
                ('curr_ult_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='max_atk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_def',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_res',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='max_spd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_atk_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Attack'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_def_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Defend'),
        ),
        migrations.AlterField(
            model_name='character',
            name='base_ult_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Ultimate'),
        ),
        migrations.AddField(
            model_name='unit',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Character'),
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Member'),
        ),
    ]
